build: off

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: if %PYTHON_VERSION% == 2.7 pip install enum34 mock
  - "pip install -r requirements.txt"
  - "python setup.py install"

test_script:
  - "python setup.py test"

